class CustomAssertionError(Exception):
    """
    To throw when an expected error occurs because of user's fault.
    """

    pass
